BUILDINGS = 'buildings'
RESOURCES = 'resources'
FACILITIES = 'station'

#Resources buildings
PRODUCTION = 'building'
STORAGE = 'storage'
METAL_MINE = 'metalMine'
CRISTAL_MINE = 'cristalMine'
DEUTERIUM_MINE = 'deuteriumMine'
SOLAR_PLANT = 'solarPlant'
FISSION_PLANT = 'fissionPlant'
METAL_SILO = 'metalSilo'
CRISTAL_SILO = 'cristalSilo'
DEUTERIUM_SILO = 'deuteriumSilo'
RESOURCES_BUILDINGS = [METAL_MINE, CRISTAL_MINE, DEUTERIUM_MINE, SOLAR_PLANT,
                       FISSION_PLANT, METAL_SILO, CRISTAL_SILO, DEUTERIUM_SILO]
#Facilities
STATION_BUILDING = 'stationbuilding'
ROBOTICS_FACTORY = 'roboticsFactory'
SHIPYARD = 'shipyard'
RESEARCH_LAB = 'researchLab'
ALLIANCE_DEPOT = 'allianceDepot'
MISSILE_SILO = 'missileSilo'
NANITE_FACTORY = 'naniteFactory'
TERRAFORMER = 'terraformer'
SPACE_DOCK = 'spaceDock'
FACILITIES_BUILDINGS = [ROBOTICS_FACTORY, SHIPYARD, RESEARCH_LAB, ALLIANCE_DEPOT,
                        MISSILE_SILO,NANITE_FACTORY, TERRAFORMER, SPACE_DOCK]


buildingTranslation = {
    #Resources
    METAL_MINE : (RESOURCES, PRODUCTION, 'supply1'),
    CRISTAL_MINE : (RESOURCES, PRODUCTION, 'supply2'),
    DEUTERIUM_MINE : (RESOURCES, PRODUCTION, 'supply3'),
    SOLAR_PLANT : (RESOURCES, PRODUCTION, 'supply4'),
    FISSION_PLANT : (RESOURCES, PRODUCTION, 'supply12'),
    METAL_SILO : (RESOURCES, STORAGE, 'supply22'),
    CRISTAL_SILO : (RESOURCES, STORAGE, 'supply23'),
    DEUTERIUM_SILO : (RESOURCES, STORAGE, 'supply24'),
    #Facilities
    ROBOTICS_FACTORY : (FACILITIES, STATION_BUILDING, 'station14'),
    SHIPYARD : (FACILITIES, STATION_BUILDING, 'station21'),
    RESEARCH_LAB : (FACILITIES, STATION_BUILDING, 'station31'),
    ALLIANCE_DEPOT : (FACILITIES, STATION_BUILDING, 'station34'),
    MISSILE_SILO : (FACILITIES, STATION_BUILDING, 'station44'),
    NANITE_FACTORY : (FACILITIES, STATION_BUILDING, 'station15'),
    TERRAFORMER : (FACILITIES, STATION_BUILDING, 'station33'),
    SPACE_DOCK : (FACILITIES, STATION_BUILDING, 'station36')
}
